package com.dapperdrakes.dimo.model;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department")
public class Department implements java.io.Serializable {

	private int id;
	private String name;
	private String creditId;
	

	public Department() {
	}

	public Department(int id) {
		this.id = id;
	}

	public Department(int id, String name, String creditId) {
		this.id = id;
		this.name = name;
		this.creditId = creditId;
		
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreditId() {
		return this.creditId;
	}

	public void setCreditId(String creditId) {
		this.creditId = creditId;
	}

	

}
