package com.dapperdrakes.dimo.model;

/**
 * Keywords generated by hbm2java
 */

public class Keywords implements java.io.Serializable {

	private int id;
	private String name;

	public Keywords() {
	}

	public Keywords(int id) {
		this.id = id;
	}

	public Keywords(int id, String name) {
		this.id = id;
		this.name = name;
		
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}



}
