package com.dapperdrakes.dimo.model;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

/**
 * MovieSpokenLang generated by hbm2java
 */
@Entity
@Table(name="movie_spoken_lang")
public class MovieSpokenLang implements java.io.Serializable {

	private Movies movies;
	private SpokenLang spokenLang;

	public MovieSpokenLang() {
	}


	public MovieSpokenLang(Movies movies, SpokenLang spokenLang) {
		this.movies = movies;
		this.spokenLang = spokenLang;
	}


	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	public SpokenLang getSpokenLang() {
		return this.spokenLang;
	}

	public void setSpokenLang(SpokenLang spokenLang) {
		this.spokenLang = spokenLang;
	}

}
