package com.dapperdrakes.dimo.model;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

/**
 * MovieProdCompany generated by hbm2java
 */
@Entity
@Table(name = "movie_prod_company")
public class MovieProdCompany implements java.io.Serializable {

	private Movies movies;
	private ProdCompany prodCompany;

	public MovieProdCompany() {
	}

	public MovieProdCompany(Movies movies, ProdCompany prodCompany) {

		this.movies = movies;
		this.prodCompany = prodCompany;
	}

	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	public ProdCompany getProdCompany() {
		return this.prodCompany;
	}

	public void setProdCompany(ProdCompany prodCompany) {
		this.prodCompany = prodCompany;
	}

}
