package com.dapperdrakes.dimo.model;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

/**
 * MovieProdCountry generated by hbm2java
 */
@Entity
@Table(name="movie_prod_country")
public class MovieProdCountry implements java.io.Serializable {

	
	private Movies movies;
	private ProdCountry prodCountry;

	public MovieProdCountry() {
	}


	public MovieProdCountry(Movies movies, ProdCountry prodCountry) {
		this.movies = movies;
		this.prodCountry = prodCountry;
	}


	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	public ProdCountry getProdCountry() {
		return this.prodCountry;
	}

	public void setProdCountry(ProdCountry prodCountry) {
		this.prodCountry = prodCountry;
	}

}
