package com.dapperdrakes.dimo.model;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

/**
 * MovieKeywords generated by hbm2java
 */
@Entity
@Table(name="movie_keywords")
public class MovieKeywords implements java.io.Serializable {

	
	private Keywords keywords;
	private Movies movies;

	public MovieKeywords() {
	}

	public MovieKeywords(Keywords keywords, Movies movies) {
		
		this.keywords = keywords;
		this.movies = movies;
	}


	public Keywords getKeywords() {
		return this.keywords;
	}

	public void setKeywords(Keywords keywords) {
		this.keywords = keywords;
	}

	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

}
