package com.dapperdrakes.dimo.model;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

/**
 * MovieGenre generated by hbm2java
 */
@Entity
@Table(name="movie_genre")
public class MovieGenre implements java.io.Serializable {


	private Genre genre;
	private Movies movies;

	public MovieGenre() {
	}

	

	public MovieGenre(Genre genre, Movies movies) {
		this.genre = genre;
		this.movies = movies;
	}


	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

}
