package com.dapperdrakes.dimo.model;


import java.math.BigDecimal;
import java.time.LocalDateTime;

// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Movies generated by hbm2java
 */
public class Movies implements java.io.Serializable {

	private int id;
	private String title;
	private Integer budget;
	private String homepage;
	private String origLang;
	private String origTitle;
	private String overview;
	private BigDecimal popularity;
	private LocalDateTime releaseDate;
	private Integer revenue;
	private Integer runtime;
	private String status;
	private String tagline;
	private BigDecimal voteAverage;
	private Integer voteCount;


	public Movies() {
	}

	public Movies(int id) {
		this.id = id;
	}

	public Movies(int id, String title, Integer budget, String homepage, String origLang, String origTitle,
			String overview, BigDecimal popularity, LocalDateTime releaseDate, Integer revenue, Integer runtime, String status,
			String tagline, BigDecimal voteAverage, Integer voteCount) {
		this.id = id;
		this.title = title;
		this.budget = budget;
		this.homepage = homepage;
		this.origLang = origLang;
		this.origTitle = origTitle;
		this.overview = overview;
		this.popularity = popularity;
		this.releaseDate = releaseDate;
		this.revenue = revenue;
		this.runtime = runtime;
		this.status = status;
		this.tagline = tagline;
		this.voteAverage = voteAverage;
		this.voteCount = voteCount;
		
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getBudget() {
		return this.budget;
	}

	public void setBudget(Integer budget) {
		this.budget = budget;
	}

	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	public String getOrigLang() {
		return this.origLang;
	}

	public void setOrigLang(String origLang) {
		this.origLang = origLang;
	}

	public String getOrigTitle() {
		return this.origTitle;
	}

	public void setOrigTitle(String origTitle) {
		this.origTitle = origTitle;
	}

	public String getOverview() {
		return this.overview;
	}

	public void setOverview(String overview) {
		this.overview = overview;
	}

	public BigDecimal getPopularity() {
		return this.popularity;
	}

	public void setPopularity(BigDecimal popularity) {
		this.popularity = popularity;
	}

	public LocalDateTime getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(LocalDateTime releaseDate) {
		this.releaseDate = releaseDate;
	}

	public Integer getRevenue() {
		return this.revenue;
	}

	public void setRevenue(Integer revenue) {
		this.revenue = revenue;
	}

	public Integer getRuntime() {
		return this.runtime;
	}

	public void setRuntime(Integer runtime) {
		this.runtime = runtime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTagline() {
		return this.tagline;
	}

	public void setTagline(String tagline) {
		this.tagline = tagline;
	}

	public BigDecimal getVoteAverage() {
		return this.voteAverage;
	}

	public void setVoteAverage(BigDecimal voteAverage) {
		this.voteAverage = voteAverage;
	}

	public Integer getVoteCount() {
		return this.voteCount;
	}

	public void setVoteCount(Integer voteCount) {
		this.voteCount = voteCount;
	}

	
}
