package com.dapperdrakes.dimo.model;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

/**
 * MovieCast generated by hbm2java
 */
@Entity
@Table(name="movie_cast")
public class MovieCast implements java.io.Serializable {

	
	private Integer id;
	private String characterName;
	private Movies movies;
	private Person person;

	public MovieCast() {
	}

	public MovieCast(Integer id, String characterName, Movies movies, Person person) {
		super();
		this.id = id;
		this.characterName = characterName;
		this.movies = movies;
		this.person = person;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCharacterName() {
		return characterName;
	}

	public void setCharacterName(String characterName) {
		this.characterName = characterName;
	}

	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
