package com.dapperdrakes.dimo.model;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

/**
 * PersonRoles generated by hbm2java
 */
@Entity
@Table(name="person_roles")
public class PersonRoles implements java.io.Serializable {

	private String roleName;
	private Department department;
	private Movies movies;
	private Person person;

	public PersonRoles() {
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public PersonRoles(String roleName, Department department, Movies movies, Person person) {
		super();
		this.roleName = roleName;
		this.department = department;
		this.movies = movies;
		this.person = person;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
