package com.dapperdrakes.dimo.model;

import javax.persistence.Entity;
import javax.persistence.Table;

// default package
// Generated 28 Jan, 2020 10:13:23 AM by Hibernate Tools 5.4.7.Final

/**
 * Preferences generated by hbm2java
 */
@Entity
@Table(name="preferences")
public class Preferences implements java.io.Serializable {

	private Genre genre;
	private Person person;
	private ProdCompany prodCompany;
	private SpokenLang spokenLang;

	public Preferences() {
	}


	public Preferences(Genre genre, Person person, ProdCompany prodCompany, SpokenLang spokenLang) {
		this.genre = genre;
		this.person = person;
		this.prodCompany = prodCompany;
		this.spokenLang = spokenLang;
	}

	

	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public ProdCompany getProdCompany() {
		return this.prodCompany;
	}

	public void setProdCompany(ProdCompany prodCompany) {
		this.prodCompany = prodCompany;
	}

	public SpokenLang getSpokenLang() {
		return this.spokenLang;
	}

	public void setSpokenLang(SpokenLang spokenLang) {
		this.spokenLang = spokenLang;
	}

}
