package com.dapperdrakes.dimo.model;

/**
 * ProdCompany generated by hbm2java
 */

public class ProdCompany implements java.io.Serializable {

	private int id;
	private String name;

	public ProdCompany() {
	}

	public ProdCompany(int id, String name) {
		this.id = id;
		this.name = name;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

}
