package com.dapperdrakes.dimo.model;

import java.util.Set;

/**
 * ProdCountry generated by hbm2java
 */

public class ProdCountry implements java.io.Serializable {

	private int id;
	private String name;

	public ProdCountry() {
	}

	public ProdCountry(int id) {
		this.id = id;
	}

	public ProdCountry(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

}
